### ISSUE TITLE
Modal ao sair da pagina - Implementar

### ISSUE THREAD

**Issue by web-fr** [tiesco-assis/single-page#3]
@tiesco-assis 
Crie uma modal com:
- Imagem do lado esquerdo
- Texto do lado direito com um cta da cor azul com a frase (Contato pelo WhatsApp (Logo WhatsApp))

**Comment by tiesco-assis** [comment]
@web-fr 
Ok, está em minha rota do projeto.

**Comment by tiesco-assis** [comment]
@web-fr .

Modal implementada.
